memory_limit = 512M
upload_max_filesize = 16M
post_max_size = 16M
max_execution_time = 60
date.timezone = America/Sao_Paulo

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
